<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLuljA0E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLuljA0E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLuljA0E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLuljA0E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLuljA0E\App_KernelDevDebugContainer([
    'container.build_hash' => 'LuljA0E',
    'container.build_id' => '7b59cb09',
    'container.build_time' => 1631889730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLuljA0E');
